name: "CDAS CD workflow: Docker Image Publish for Go App"
run-name: "Build and publish to Docker Hub"

on:
  workflow_run:
    workflows: ["CDAS CI Workflow for Go"]
    types:
      - completed

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Extract short SHA
      id: vars
      run: echo "GIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/cdas-exercise:latest -t ${{ secrets.DOCKER_HUB_USERNAME }}/cdas-exercise:${{ env.GIT_SHA }} .

    - name: Push Docker image (latest + GIT SHA)
      run: |
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/cdas-exercise:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/cdas-exercise:${{ env.GIT_SHA }}
